name: plato_paper
description: A collection of Plato elements, based on Polymer's core and paper elements for Material Design.
dependencies:
  core_elements: '>=0.4.0+2 <0.5.0'
  crypto: '>=0.9.0 <0.10.0'
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.1+3 <0.16.0'
  unittest: '>=0.11.0+5 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      web/plato-paper-common.css: false
