name: plato.paper
version: 0.0.1
description: A collection of Plato elements, based on Polymer's core and paper elements for Material Design.
dependencies:
  core_elements: '^0.7.1+2'
  crypto: '>=0.9.0 <0.10.0'
  paper_elements: '^0.7.1+1'
  polymer: '^0.16.3+3'
  unittest: '>=0.11.0+5 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      web/style/plato-paper-common.css: false
